name: Test and Build

on: [push, workflow_dispatch]

jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: ['linux','windows']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'
      - name: Test
        run: go test -v ./...
      - name: Build ${{ matrix.GOOS }}
        run: GOOS=${{ matrix.GOOS }} go build  -o anagramalyser-${{ matrix.GOOS }} ./cmd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.GOOS }}
          path: anagramalyser-${{ matrix.GOOS }}